/**
 * @aiq.webdesigner
 * This script requires AIQ Web Designer
*/
setShadowDOM(true);
addSmartTagsLibrary("{ds}/Smart Tags/Newsmarttag.stags");
navigateTo("https://demosite.appvance.net/");
click(fallback(`span(0, _in(div("product_1")))`,
   `span(0, _in(div({'id':'product_1'})))`,
   `span("Ruby on Rails Tote")`,
   `span("info")`,
   `span("Ruby on Rails Tote")`,
   `byXPath("//div[@id='product_1']/div/div[1]/a/span")`,
   `byXPath('//*[@class="info"]')`,
   `byXPath('//*[text()="Ruby on Rails Tote"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div/a/span')`,
   `byXPath("id('product_1')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/span[@class='info']")`,
   `span({'itemprop':'name'})`,
   `byJQuery('span[title="Ruby on Rails Tote"]')`,
   `byJQuery('span[class="info"]')`,
   `byJQuery('.info')`));
setValue(fallback(`Newsmarttag_01('quantity')`,
   `byXPath('//*[@id="quantity"]')`,
   `numberbox("form-control title")`,
   `byXPath('//*[@name="quantity"]')`,
   `numberbox("quantity")`,
   `numberbox("quantity")`,
   `byXPath("//input[@id='quantity']")`,
   `byXPath('//*[@class="title form-control"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/input')`,
   `byXPath("id('quantity')")`,
   `numberbox({'min':'1'})`,
   `byJQuery('div[class="row"] > div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > input[class="title form-control"]')`,
   `byJQuery('#quantity')`,
   `byJQuery('input[name="quantity"]')`),"2");
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/span/button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byJQuery('#add-to-cart-button')`,
   `byJQuery('button[name="button"]')`));
click(fallback(`link(0, _in(paragraph("clear_cart_link")))`,
   `link(0, _in(paragraph({'id':'clear_cart_link'})))`,
   `link("continue")`,
   `link("/products")`,
   `link("Continue shopping")`,
   `byXPath("//p[@id='clear_cart_link']/a")`,
   `byXPath('//*[@class="continue"]')`,
   `byXPath('//*[text()="Continue shopping"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/form/p/a')`,
   `byXPath("id('clear_cart_link')/a[@class='continue']")`,
   `byJQuery('a[class="continue"]')`,
   `byJQuery('#clear_cart_link > .continue')`,
   `byJQuery('a[href="/products"]')`));
